### ISSUE TITLE
Friends yourself

### ISSUE THREAD

**Issue by SenseiTarzan** [wow0000/friends42#4]
We can, I add, even as a friend 
![Screenshot_20230918-115932](https://github.com/wow0000/friends42/assets/32621158/307c88ac-3d8e-41b4-b966-a0020106e90e)
![Screenshot_20230918-115940](https://github.com/wow0000/friends42/assets/32621158/3a922a7b-cc96-4127-8036-f51615560237)

**Comment by wow0000** [comment]
Hello !
Thank you for your bug report, however this is a feature, It is used to test features such as notifications without annoying anyone ! :)

**Comment by SenseiTarzan** [comment]
You should create a tag system that will allow you to activate access to the test environment
